name: PR check

on: 
  workflow_dispatch: 
      
jobs:
  pr-check:
    runs-on: ubuntu-lastest

  steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Print PR branch
      run: echo "PR check running for branch ${{ github.head_ref }}"
